"""Open Chicken (crazy_chick): robot constants on the microduck skeleton.

The crazy_chick keeps microduck's kinematics/actuator layout un-scaled and adds:
  * a 40mm EDF ducted-fan motor (edf_thrust, thrust line through CoM),
  * knee/ankle springs (joint stiffness + springref).
The hardware swap Dynamixel XL330 -> Feetech STS3215 is represented here by
pointing the BAM M6 actuator at the STS3215 parameters identified by
Open_Duck_Mini (experiments/v2/params_m6.json, 7.4V bench) via ``json_path``.
"""

from __future__ import annotations

import os
from pathlib import Path

import mujoco
from mjlab.actuator import XmlActuatorCfg
from mjlab.actuator.actuator import TransmissionType
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab_microduck.actuator import (
    BacklashEncoderBamActuatorCfg,
    FrictionDRBamActuatorCfg,
)
from mjlab_microduck.robot.microduck_constants import (
    BACKLASH_HOME_FRAME,
    FULL_COLLISION,
    HOME_FRAME,
)


_ROBOT_DIR: Path = Path(os.path.dirname(__file__))

# MJCF generated by make_crazy_chick.py (microduck model matrix + EDF + springs).
CRAZY_CHICK_WALK_XML: Path = _ROBOT_DIR / "crazy_chick_walk.xml"
CRAZY_CHICK_ALLCOLLISIONS_XML: Path = _ROBOT_DIR / "crazy_chick_allcollisions.xml"
CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_XML: Path = _ROBOT_DIR / "crazy_chick_allcollisions_rollers.xml"
CRAZY_CHICK_WALK_BACKLASH_XML: Path = _ROBOT_DIR / "crazy_chick_walk_backlash.xml"
CRAZY_CHICK_ALLCOLLISIONS_BACKLASH_XML: Path = _ROBOT_DIR / "crazy_chick_allcollisions_backlash.xml"
CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_BACKLASH_XML: Path = (
    _ROBOT_DIR / "crazy_chick_allcollisions_rollers_backlash.xml"
)
# STS3215 M6 parameters, bench-identified by Open_Duck_Mini @ 7.4V
# (experiments/v2/params_m6.json). v0; re-fit on the actual servos (P2 bench).
STS3215_M6_PARAMS_JSON: Path = _ROBOT_DIR / "assets" / "params_sts3215_m6.json"

for _p in (
    CRAZY_CHICK_WALK_XML,
    CRAZY_CHICK_ALLCOLLISIONS_XML,
    CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_XML,
    CRAZY_CHICK_WALK_BACKLASH_XML,
    CRAZY_CHICK_ALLCOLLISIONS_BACKLASH_XML,
    CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_BACKLASH_XML,
):
    assert _p.exists(), f"XML not found: {_p}"
assert STS3215_M6_PARAMS_JSON.exists(), f"params not found: {STS3215_M6_PARAMS_JSON}"


def get_crazy_chick_walk_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_WALK_XML))


def get_crazy_chick_allcollisions_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_ALLCOLLISIONS_XML))


def get_crazy_chick_rollers_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_XML))


def get_crazy_chick_walk_backlash_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_WALK_BACKLASH_XML))


def get_crazy_chick_backlash_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_ALLCOLLISIONS_BACKLASH_XML))


def get_crazy_chick_rollers_backlash_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(CRAZY_CHICK_ALLCOLLISIONS_ROLLERS_BACKLASH_XML))


# -- BAM M6 actuator for Feetech STS3215 --
# Same shape as microduck's _BAM_ACTUATOR_KWARGS, but the motor parameters come
# from the STS3215 identification JSON (json_path; mutually exclusive with
# motor_name/model). kp_fw 2026-09-05 曾误设 9.5=OpenDuck robot.xml 的
# <position kp="9.5">，但那是 MuJoCo position 舵机 kp，而 BAM 电压模型里
# kp_fw 是【固件 P 增益】，二者单位不同 → 实际刚度 kp_fw×0.166 仅 ~1.58 duty/rad，
# 软到策略平衡不住只能碎挪（match 1.25，v12-v14 退化根因）。bam 库给 STS3215 的
# 真实固件 kp=32（示波器实测，见 bam/feetech/actuator.py）→ 刚度 ~5.31 duty/rad。
# 改回 32（真实值，去错配）；原 microduck/XL330 占位 200（刚度 33.2）过于生硬。
# vin_range centred on 7.4V (STS3215 nominal 2S); identification done at 7.4V.
STS3215_BAM_ACTUATOR_KWARGS = dict(
    json_path=str(STS3215_M6_PARAMS_JSON),
    target_names_expr=(r"^(?!passive_).*",),
    kp_fw=32.0,  # STS3215 真实固件 kp（bam 库默认，示波器实测）；修复 9.5 错配
    vin_range=(7.0, 7.9),  # 7.4V nominal 2S
    vin_drop_gain_range=(0.0, 0.2),
    vin_min=6.0,
    delay_min_lag=3,
    delay_max_lag=6,
)
sts3215_actuators = FrictionDRBamActuatorCfg(**STS3215_BAM_ACTUATOR_KWARGS)

# Encoder-through-backlash variant for the backlash model (mirrors microduck).
sts3215_backlash_actuators = BacklashEncoderBamActuatorCfg(
    **STS3215_BAM_ACTUATOR_KWARGS
)

# EDF thruster: the XML already defines <motor name="edf_thrust" site="edf_exit"
# gear="0 0 1" ctrlrange="0 1"/>. Claim it with a SITE-transmission
# XmlActuatorCfg so mjlab allocates site_effort_target (has_site_actuators) and
# the SiteEffortAction can drive the motor ctrl (= thrust multiplier).
# Without this claim, the site-bound motor is invisible to the action manager.
edf_actuator = XmlActuatorCfg(
    target_names_expr=("edf_exit",),
    transmission_type=TransmissionType.SITE,
)

# Walk model: microduck skeleton + EDF motor (XML, site-bound) + STS3215 BAM on
# the 14 servo joints -> action space 15D (14 joints + edf_duty).
CRAZY_CHICK_WALK_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_walk_spec,
    init_state=HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)

# Full-collision variant (standup / ground-pick family). Mirrors
# MICRODUCK_STANDUP_ROBOT_CFG.
CRAZY_CHICK_STANDUP_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_allcollisions_spec,
    init_state=HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)

# Roller-skate variant: 4 passive wheel joints (passive_*wheel) stay free, no
# XML actuators; the BAM target regex already excludes them. collisions=()
# mirrors MICRODUCK_WALK_ROLLERS_ROBOT_CFG.
CRAZY_CHICK_ROLLERS_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_rollers_spec,
    init_state=HOME_FRAME,
    collisions=(),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)

# Backlash variants: ±1° serial backlash hinge per servo (passive_*_backlash),
# encoder reads through the play (BacklashEncoderBamActuator) and the backlash
# joints are pinned at 0 by BACKLASH_HOME_FRAME. Mirrors microduck's
# BACKLASH / WALK_BACKLASH / ROLLERS_BACKLASH robot cfgs.
CRAZY_CHICK_BACKLASH_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_backlash_spec,
    init_state=BACKLASH_HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_backlash_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)

CRAZY_CHICK_WALK_BACKLASH_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_walk_backlash_spec,
    init_state=BACKLASH_HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_backlash_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)

CRAZY_CHICK_ROLLERS_BACKLASH_ROBOT_CFG = EntityCfg(
    spec_fn=get_crazy_chick_rollers_backlash_spec,
    init_state=BACKLASH_HOME_FRAME,
    collisions=(),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_backlash_actuators, edf_actuator),
        soft_joint_pos_limit_factor=0.9,
    ),
)
