"""Open Duck (SolidWorks export): robot constants for the mjlab training pipeline.

open_duck_walk.xml is generated from the user's SolidWorks SW2URDF export
(open_duck.urdf) by make_open_duck.py in this directory: the root is
uprighted, left/right joint axes are mirror-symmetric, and the CAD inertias +
visual meshes are preserved. The morphology matches the microduck joint-name
contract (14 servos; NO EDF — the Open Duck policy is pure joint control, so
the model is generated with INCLUDE_EDF=False and nu == 14 == action dim).
The STS3215 BAM actuators from crazy_chick are reused verbatim — the hardware
is the same Feetech STS3215 family.
"""

from __future__ import annotations

import os
from pathlib import Path

import mujoco
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg

from mjlab_microduck.robot.crazy_chick.crazy_chick_constants import (
    sts3215_actuators,
)
from mjlab_microduck.robot.microduck_constants import FULL_COLLISION

_ROBOT_DIR: Path = Path(os.path.dirname(__file__))

# MJCF generated by urdf2mjcf.py (SolidWorks Open Duck + uprighted root).
OPEN_DUCK_WALK_XML: Path = _ROBOT_DIR / "open_duck_walk.xml"

assert OPEN_DUCK_WALK_XML.exists(), f"XML not found: {OPEN_DUCK_WALK_XML}"


def get_open_duck_walk_spec() -> mujoco.MjSpec:
    return mujoco.MjSpec.from_file(str(OPEN_DUCK_WALK_XML))


# mjlab's init_state OVERRIDES the freejoint qpos with (pos, rot); its defaults
# (origin, identity quat) would replace the XML's baked upright root orientation
# and spawn the robot lying down. So the init_state must carry the same root
# quat as the XML's trunk_base (that IS the upright home frame) plus the zero
# joint pose, which was verified statically stable (CoM inside the foot support
# polygon, strong-PD hold keeps trunk_z constant).
#
# NOTE (2026-09-02, root cause of the failed 10k-iter run): pos must stay (0,0,0).
# The XML trunk_base pos already carries the converter shift
# (-0.1076, -0.0236, 0.1222), so the robot's feet rest on the floor at qpos0
# (freejoint qpos == 0). mjlab's reset_base adds pose_range ON TOP of
# default_root_state, so a non-zero init_state.pos double-raises the root
# (~+0.12 m) and the robot spawns airborne -> guaranteed fall on step 1.
OPEN_DUCK_HOME_FRAME = EntityCfg.InitialStateCfg(
    pos=(0.0, 0.0, 0.0),  # must be zero: XML trunk_base pos already places feet on floor
    rot=(-0.2071533, 0.124947992, 0.586534625, 0.772950608),  # trunk_base XML quat — upright
    joint_pos={r".*": 0.0},  # zero pose: legs straight, head level
    joint_vel={".*": 0.0},
)

# Walk model: SolidWorks Open Duck, 14 servo joints (STS3215 BAM, same as
# crazy_chick), no EDF -> action space 14D (pure joint control), nu == 14.
# FULL_COLLISION matches the foot collision geoms (left_foot_collision /
# right_foot_collision) with condim=3 + priority=1, exactly like crazy_chick.
OPEN_DUCK_WALK_ROBOT_CFG = EntityCfg(
    spec_fn=get_open_duck_walk_spec,
    init_state=OPEN_DUCK_HOME_FRAME,
    collisions=(FULL_COLLISION,),
    articulation=EntityArticulationInfoCfg(
        actuators=(sts3215_actuators,),
        soft_joint_pos_limit_factor=0.9,
    ),
)


if __name__ == "__main__":
    import mujoco.viewer as viewer
    from mjlab.scene import Scene, SceneCfg
    from mjlab.terrains import TerrainImporterCfg

    SCENE_CFG = SceneCfg(
        terrain=TerrainImporterCfg(terrain_type="plane"),
        entities={"robot": OPEN_DUCK_WALK_ROBOT_CFG},
    )

    scene = Scene(SCENE_CFG, device="cuda:0")
    viewer.launch(scene.compile())
